version: "3"

services:

  runtime-setup:
    image: swift-distributed-tracing:20.04-5.8
    build:
      args:
        base_image: "swiftlang/swift:nightly-5.8-focal"

  test:
    image: swift-distributed-tracing:20.04-5.8
    environment:
      - FORCE_TEST_DISCOVERY=--enable-test-discovery

  shell:
    image: swift-distributed-tracing:20.04-5.8
