version: "3"

services:

  runtime-setup:
    image: swift-distributed-tracing:18.04-5.2

  test:
    image: swift-distributed-tracing:18.04-5.2
    environment: []
      #- SANITIZER_ARG=--sanitize=thread

  shell:
    image: swift-distributed-tracing:18.04-5.2
