# this file is not designed to be run directly
# instead, use the docker-compose.<os>.<swift> files
# eg docker-compose -f docker/docker-compose.yaml -f docker/docker-compose.1804.50.yaml run test
version: "3"

services:

  runtime-setup:
    image: swift-distributed-tracing:default
    build:
      context: .
      dockerfile: Dockerfile

  common: &common
    image: swift-distributed-tracing:default
    depends_on: [runtime-setup]
    volumes:
      - ~/.ssh:/root/.ssh
      - ..:/code:z
    working_dir: /code
    cap_drop:
      - CAP_NET_RAW
      - CAP_NET_BIND_SERVICE

  soundness:
    <<: *common
    command: /bin/bash -xcl "./scripts/soundness.sh"

  test:
    <<: *common
    # FIXME: We cannot use -warnings-as-errors because we inherit from a deprecated type in the Tracer type,
    #        and we need to keep supporting the old type still. This was introduced as we dropped Swift 5.6 and added 5.9/5.10.
    command: /bin/bash -xcl "swift test $${FORCE_TEST_DISCOVERY-} $${SANITIZER_ARG-} $${STRICT_CONCURRENCY_ARG-}"

  # util

  shell:
    <<: *common
    entrypoint: /bin/bash
