version: "3"

services:

  runtime-setup:
    image: swift-distributed-tracing:20.04-5.8
    build:
      args:
        ubuntu_version: "focal"
        swift_version: "5.8"

  test:
    image: swift-distributed-tracing:20.04-5.8
    environment:
      - FORCE_TEST_DISCOVERY=--enable-test-discovery
      # - STRICT_CONCURRENCY_ARG=-Xswiftc -strict-concurrency=complete

  shell:
    image: swift-distributed-tracing:20.04-5.8
