# this file is not designed to be run directly
# instead, use the docker-compose.<os>.<swift> files
# eg docker-compose -f docker/docker-compose.yaml -f docker/docker-compose.1804.50.yaml run test
version: "3"

services:

  runtime-setup:
    image: swift-distributed-tracing:default
    build:
      context: .
      dockerfile: Dockerfile

  common: &common
    image: swift-distributed-tracing:default
    depends_on: [runtime-setup]
    volumes:
      - ~/.ssh:/root/.ssh
      - ..:/code:z
    working_dir: /code
    cap_drop:
      - CAP_NET_RAW
      - CAP_NET_BIND_SERVICE

  sanity:
    <<: *common
    command: /bin/bash -xcl "./scripts/sanity.sh"

  docs:
    <<: *common
    environment:
      - CI
    command: /bin/bash -xcl "./scripts/generate_docs.sh"

  test:
    <<: *common
    security_opt: # FIXME: temp while private
      - label=type:container_runtime_t
    volumes: # FIXME: temp while private
      - ..:/code:z
      - ~/.ssh:/root/.ssh
      - $SSH_AUTH_SOCK:/tmp/ssh-agent:z
    environment: # FIXME: temp while private
      - SSH_AUTH_SOCK=/tmp/ssh-agent
      - GIT_SSH_COMMAND=ssh -vv -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no    
    command: /bin/bash -xcl "swift test -Xswiftc -warnings-as-errors $${SANITIZER_ARG-}"

  # util

  shell:
    <<: *common
    entrypoint: /bin/bash
