name: PR

permissions:
  contents: read

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  soundness:
    name: Soundness
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@main
    with:
      license_header_check_project_name: "Swift Distributed Tracing"

  # FIXME: We cannot use -warnings-as-errors because we inherit from a deprecated type in the Tracer type,
  #        and we need to keep supporting the old type still. This was introduced as we dropped Swift 5.6 and added 5.9/5.10.
  unit-tests:
    name: Unit tests
    uses: apple/swift-nio/.github/workflows/unit_tests.yml@main
    with:

      # NOTE: Aug 5, 2025. We've determined SPM has bugs for `condition: .when(platforms: [.somePlatform])`
      # that incorrectly ignore the condition and import anyways for unintended platforms.
      #
      # See https://github.com/apple/swift-distributed-tracing/actions/runs/16578688393/job/46920025183?pr=174
      # for an example of the resulting build failure.
      #
      # This is documented as a bug in Swift 5.10, resolved in Swift 6.
      # See FB14859516.
      # See also https://forums.swift.org/t/do-swiftpm-conditional-target-dependencies-work/74047
      #
      # Given this, the explicit target dependency check is disabled for Swift versions before Swift 6.

      # Intentionally disabled:
      #
      # linux_5_9_arguments_override: "--explicit-target-dependency-import-check error"
      # linux_5_10_arguments_override: "--explicit-target-dependency-import-check error"

      linux_6_0_arguments_override: "--explicit-target-dependency-import-check error -Xswiftc -require-explicit-sendable"
      linux_6_1_arguments_override: "--explicit-target-dependency-import-check error -Xswiftc -require-explicit-sendable"
      linux_6_2_arguments_override: "--explicit-target-dependency-import-check error -Xswiftc -require-explicit-sendable"
      linux_nightly_6_0_arguments_override: "--explicit-target-dependency-import-check error -Xswiftc -require-explicit-sendable"
      linux_nightly_main_arguments_override: "--explicit-target-dependency-import-check error -Xswiftc -require-explicit-sendable"
      windows_6_0_enabled: true
      windows_6_1_enabled: true
      windows_nightly_next_enabled: true
      windows_nightly_main_enabled: true
      windows_6_0_arguments_override: "--explicit-target-dependency-import-check error -Xswiftc -require-explicit-sendable"
      windows_6_1_arguments_override: "--explicit-target-dependency-import-check error -Xswiftc -require-explicit-sendable"
      windows_nightly_next_arguments_override: "--explicit-target-dependency-import-check error -Xswiftc -require-explicit-sendable"
      windows_nightly_main_arguments_override: "--explicit-target-dependency-import-check error -Xswiftc -require-explicit-sendable"

  benchmarks:
    name: Benchmarks
    uses: apple/swift-nio/.github/workflows/benchmarks.yml@main
    with:
      benchmark_package_path: "Benchmarks"

  cxx-interop:
    name: Cxx interop
    uses: apple/swift-nio/.github/workflows/cxx_interop.yml@main

  release-builds:
    name: Release builds
    uses: apple/swift-nio/.github/workflows/release_builds.yml@main
